name: Promote most recent branch to main
on:
  push:
    branches: ['**']
    paths-ignore: ['README.md', 'docs/**', '.github/**']   # optional
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # optional

permissions:
  contents: write
  pull-requests: write
jobs:
  pick-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - run: |
          set -euo pipefail
          git fetch --all --prune

          # pick newest remote branch excluding main and HEAD
          latest=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin \
                   | grep -vE '^origin/(HEAD|main)$' | head -n1)
          echo "Candidate: $latest"
          [ -z "$latest" ] && echo "No candidate branch" && exit 0

          # ensure main can fast-forward
          git switch -c work origin/main
          if git merge --ff-only "$latest"; then
            echo "Fast-forwarding main to $latest"
            git push origin HEAD:main
          else
            echo "Cannot fast-forward main to $latest (diverged)."
            exit 1
          fi
